/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/m/button/index.vue')['default']
    FormItem: typeof import('./src/components/m/form-item/index.vue')['default']
    Input: typeof import('./src/components/m/input/index.vue')['default']
    MButton: typeof import('./src/components/m/button/index.vue')['default']
    MFormItem: typeof import('./src/components/m/form-item/index.vue')['default']
    MInput: typeof import('./src/components/m/input/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
